version: '3.0'

services:
  db:
    image: 'postgres:13-alpine'
    hostname: db
    ports:
      - '6543:5432'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  minio:
    image: 'minio/minio'
    ports:
      - '9000:9001'
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: superadmin
      MINIO_ROOT_PASSWORD: pass1234
    command: server --console-address ":9001" /data

  redis:
    image: 'redis:latest'
    container_name: redis
#    environment:
#      - REDIS_PASSWORD=my_redis_password
#      - REDIS_USER=my_user
#      - REDIS_USER_PASSWORD=my_user_password
    ports:
      - "6380:6379"
    volumes:
      - local_redisdata:/var/lib/redisdata/data

  app:
    build: .
    deploy:
      mode: replicated
      replicas: 3
    image: liceum_server/app:vtest6
    ports:
      - '9000-9003:90'
    depends_on:
      - db
      - minio
      - redis
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_MINIO_HOST=http://minio:9001/
      - SPRING_MINIO_USERNAME=superadmin
      - SPRING_MINIO_PASSWORD=pass123
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  nginx:
    image: liceum_server/nginx:vtest7
    build:
      dockerfile: nginx/Dockerfile
      context: .
    ports:
      - '8080:8080'
    restart: always
    depends_on:
      - app

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./env/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3000:3000'
    env_file:
      - ./env/grafana.env
    volumes:
      - local_grafana_data:/var/lib/grafana/data

volumes:
  local_pgdata:
  local_redisdata:
  local_grafana_data:
  minio_storage: {}