global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 5s

    static_configs:
      - targets: ['172.17.0.1:9090'] #todo change with actual docker ip
        labels:
          alias: 'prometheus'

  - job_name: 'spring_micrometer'

    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ '172.17.0.1:8080' ]

  - job_name: 'postgres'

    scrape_interval: 5s

    static_configs:
      - targets: ['172.17.0.1:5432']
        labels:
          alias: 'postgres'

  - job_name: 'redis'

    scrape_interval: 5s

    static_configs:
      - targets: [ '172.17.0.1:6379' ]
        labels:
          alias: 'redis'