global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']
        labels:
          alias: 'prometheus'

  - job_name: 'liceumServer'

    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:8080']
        labels:
          alias: 'liceumServer'

  - job_name: 'postgres'

    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:5432']
        labels:
          alias: 'postgres'